services:
  line-scs-bot-db:
    image: mysql:latest
    volumes:
    - ../db/initdb.d:/docker-entrypoint-initdb.d
    - ../db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - nsnetwork
  line-scs-bot-app:
    image: line-scs-bot:latest 
    volumes:
      - ../cmd:/go/cmd
      - ./.env:/.env
      - ./ssl:/ssl
    depends_on:
      - line-scs-bot-db
    expose:
      - "80"
    tty: true
    networks:
      - nsnetwork

networks:
  nsnetwork:
    external: true