services:
  line-scs-bot-db:
    image: mysql:latest
    volumes:
    - ../db/initdb.d:/docker-entrypoint-initdb.d
    - ../db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - nsnetwork
  line-scs-bot-app:
    image: line-scs-bot:latest 
    volumes:
      - ./.env:/.env
    depends_on:
      - line-scs-bot-db
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    tty: true
    networks:
      - nsnetwork

networks:
  nsnetwork:
    external: true